-- WARNING: This is NOT the recommended way to handle users with Supabase.
-- Supabase automatically provides a secure `auth.users` table.
-- The existing login code in this application is designed to work with `auth.users`.
-- This custom `users` table WILL NOT WORK with the current authentication flow
-- and would require building a manual, less secure login system.

-- A better practice is to create a `profiles` table to store public information
-- and link it to the `auth.users` table.

-- Create the custom table
CREATE TABLE public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT,
  email TEXT UNIQUE NOT NULL,
  -- In a real scenario, this should store a hashed password, not plain text.
  password TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add a comment to the table for clarity
COMMENT ON TABLE public.users IS 'Custom user table for CMS login. Not recommended for use with Supabase Auth.';